name: CI

on: [push]

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: actions/checkout@v2
        with:
          repository: raphtalia/Forge
          ref: development
          path: Forge

      - uses: DamianReeves/write-file-action@v1.0
        with:
          path: foreman.toml
          contents: |
            [tools]
            rojo = { source = "rojo-rbx/rojo", version = "7.0.0-alpha.4" }
            remodel = { source = "rojo-rbx/remodel", version = "0.9.0" }
          write-mode: overwrite

      - uses: Roblox/setup-foreman@v1
        with:
          version: "^1.0.0"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Report tool versions
        run: |
          rojo --version
          remodel --version

      - uses: leafo/gh-actions-lua@v8
        with:
          luaVersion: "5.3"

      - name: Install dependencies
        run: |
          luarocks install luafilesystem

      - name: Build
        run: |
          remodel run Forge/build.lua output.rbxl

      - name: Deploy
        run: |
          remodel run Forge/upload.lua output.rbxl
        env:
          REMODEL_AUTH: ${{ secrets.ROBLOSECURITY }}