name: CI

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: actions/checkout@v2
        with:
          repository: raphtalia/Forge
          path: Forge

      - uses: DamianReeves/write-file-action@master
        with:
          path: foreman.toml
          contents: |
            [tools]
            rojo = { source = "rojo-rbx/rojo", version = "7.0.0-alpha.4" }
            remodel = { source = "rojo-rbx/remodel", version = "0.9.0" }
          write-mode: overwrite

      - uses: Roblox/setup-foreman@v1
        with:
          version: "^1.0.0"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: |
          remodel run Forge/build.lua output.rbxl

      - name: Build Archival
        uses: actions/upload-artifact@v2
        with:
          name: Output
          path: output.rbxl
          retention-days: 3

      - name: Wait for tests
        uses: lewagon/wait-on-check-action@master
        with:
          ref: ${{ github.ref }}
          check-name: 'Test'
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy
        run: |
          remodel run Forge/upload.lua output.rbxl
        env:
          REMODEL_AUTH: ${{ secrets.ROBLOSECURITY }}

  test:
    name: Test
    runs-on: windows-2022

    steps:
      - uses: OrbitalOwen/roblox-win-installer-action@1.1
        with:
          cookie: ${{ secrets.ROBLOSECURITY }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: DamianReeves/write-file-action@v1.0
        with:
          path: foreman.toml
          contents: |
            [tools]
            run-in-roblox = { source = "rojo-rbx/run-in-roblox", version = "0.3.0" }
          write-mode: overwrite

      - uses: Roblox/setup-foreman@v1
        with:
          version: "^1.0.0"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Wait for build
        uses: lewagon/wait-on-check-action@v1.1.0-rc
        with:
          ref: ${{ github.ref }}
          check-name: 'Build Archival'
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/download-artifact@v2
        with:
          name: Output

      - name: Extract place file
        run: 7z x output.rbxl

      - name: Test
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 5
          max_attempts: 3
          command: run-in-roblox --place output.rbxl --script test.lua