name: Deployment

on:
  push:
    branches:
      - main
      - development

jobs:
  deployment:
    name: Deployment
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true

      - uses: Roblox/setup-foreman@v1
        with:
          version: "^1.0.0"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Report tool versions
        run: |
          rojo --version
          remodel --version

      - name: Deploy
        run: remodel run .remodel/main.lua ${GITHUB_REF#refs/heads/} ${GITHUB_SHA}
        env:
          REMODEL_AUTH: ${{ secrets.ROBLOSECURITY }}