name: Deployment

on:
  push:
    branches:
      - master

jobs:
  deployment:
    name: Deployment
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true

    - uses: Roblox/setup-foreman@v1
      with:
        version: "^1.0.0"
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: "Build place file"
      run: remodel run .remodel/main.lua

    - name: Report tool versions
      run: remodel --version
      run: rojo --version

    - name: Deploy
      run: rojo upload --cookie "$ROBLOSECURITY" --asset_id 7463431274 output
      env:
        ROBLOSECURITY: ${{ secrets.ROBLOSECURITY }}