name: Deployment

on: [push]

jobs:
  deployment:
    name: Deployment
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      # - uses: actions/checkout@v2
      #   with:
      #     repository: raphtalia/Forge

      - uses: Roblox/setup-foreman@v1
        with:
          version: "^1.0.0"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Report tool versions
        run: |
          rojo --version
          remodel --version

      - name: Deploy
        run: |
          remodel run Forge/main.lua
        env:
          REMODEL_AUTH: ${{ secrets.ROBLOSECURITY }}