name: Selene

on: [push]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - uses: DamianReeves/write-file-action@v1.0
        with:
          path: foreman.toml
          content: |
            [tools]
            selene = { source = "Kampfkarren/selene", version = "=0.11.0" }
          write-mode: overwrite

      - uses: Roblox/setup-foreman@v1
        with:
          version: "^1.0.0"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Selene
        run: selene src
